---
#
# Ansible managed
#

name: Ansible Molecule

on:
  # Schedule updates (once daily)
  schedule:
    - cron: '7 4 * * *'
  workflow_dispatch:
  push: {branches: ["master", "main", "testing"]}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: buluma/molecule-action@v4.0.6
        with:
          command: lint
  test:
    # needs:
    #   - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "docker-ubuntu-systemd"
            tag: "bionic"
          - image: "ubuntu"
            tag: "latest"
          - image: "docker-ubuntu2204-ansible"
            tag: "latest"
          - image: "docker-ubuntu2104-ansible"
            tag: "latest"
          - image: "docker-ubuntu2004-ansible"
            tag: "latest"
          - image: "ubuntu-python3"
            tag: "latest"
          - image: "ubuntu-test"
            tag: "latest"
          - image: "ubuntu-dev"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: false
          cache-version: 2
      - name: molecule
        uses: buluma/molecule-action@v4.0.6
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
